package proyectocalculo.view;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyectocalculo.model.Ecuacion;

public class VentanaCalculo extends javax.swing.JFrame {
     private Dimension dim;

    public  void metodoElipX() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/elipX.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
    
    public  void metodoParabH() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/parabH.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
    
    public  void metodoCono() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/conop.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
    
    public  void metodoHip1() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/Hip1.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
    
     public  void metodoHip2() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/Hip2.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
     
      public  void metodoElip() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/elip.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }
      
      public  void metodoEsf() {
        ImageIcon figura;
        figura = new ImageIcon(getClass().getResource("/proyectocalculo/design/esf.PNG"));
        Icon figuraIcono = new ImageIcon(figura.getImage().getScaledInstance(Figuralbl.getWidth(),Figuralbl.getHeight(),Image.SCALE_SMOOTH));
        Figuralbl.setIcon(figuraIcono);
    }

    public VentanaCalculo() {
        //con esto obtienes en tamano en en x y y de tu monitor
      /*  dim=super.getToolkit().getScreenSize();
        super.setSize(dim);
        super.setUndecorated(true);
        super.setVisible(true);
      */  
      
      //int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
     //  int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
               // super.setVisible(true);


        initComponents();
       // this.setBounds((ancho ) - (this.getWidth() ), (alto ) - (this.getHeight() ), 1000, 1000);

        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/proyectocalculo/design/logo1.png")));
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxEsfera = new javax.swing.JCheckBox();
        jLabelEsfera = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelElipse = new javax.swing.JLabel();
        jCheckBoxElipsoide = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxCono = new javax.swing.JCheckBox();
        jLabelCono = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultados = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxParaboloideEliptico = new javax.swing.JCheckBox();
        jLabelParaboloideEliptico = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxParaboloideHiperbolico = new javax.swing.JCheckBox();
        jLabelParaboloideHiperbolico = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelHiperboloideUnaHoja = new javax.swing.JLabel();
        jCheckBoxHiperboloide1Hoja = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxHiperboloide2Hojas = new javax.swing.JCheckBox();
        jLabelHiperboloideDosHojas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Figuralbl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Cálculo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Analizar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxEsfera.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxEsfera.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxEsfera.setText("Esfera");
        jCheckBoxEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEsferaActionPerformed(evt);
            }
        });

        jLabelEsfera.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabelEsfera.setText("+((x-h)^2)+((y-k)^2)+((z-l)^2)=r^2");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/EsferaP.PNG"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(342, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jCheckBoxEsfera))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEsfera)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBoxEsfera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEsfera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelElipse.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelElipse.setText("+(((x-h)^2)/a^2)+(((y-k)^2)/b^2)+(((z-l)^2)/c^2)=1");

        jCheckBoxElipsoide.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxElipsoide.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxElipsoide.setText("Elipsoide");
        jCheckBoxElipsoide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxElipsoideActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/EipsoideP.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelElipse))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jCheckBoxElipsoide)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jCheckBoxElipsoide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelElipse))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxCono.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxCono.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxCono.setText("Cono");
        jCheckBoxCono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxConoActionPerformed(evt);
            }
        });

        jLabelCono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelCono.setText("+(((x-h)^2)/a^2)+(((y-k)^2)/b^2)-(((z-l)^2)/c^2)=0");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/ConoP.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jCheckBoxCono))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jCheckBoxCono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCono))
        );

        jTextAreaResultados.setEditable(false);
        jTextAreaResultados.setColumns(20);
        jTextAreaResultados.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jTextAreaResultados.setLineWrap(true);
        jTextAreaResultados.setRows(5);
        jTextAreaResultados.setText("Resultados...");
        jTextAreaResultados.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaResultados);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxParaboloideEliptico.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxParaboloideEliptico.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxParaboloideEliptico.setText("Paraboloide Eliptico");
        jCheckBoxParaboloideEliptico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxParaboloideElipticoActionPerformed(evt);
            }
        });

        jLabelParaboloideEliptico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelParaboloideEliptico.setText("+(c*(z-l))=+(((x-h)^2)/a^2)+(((y-k)^2)/b^2) ");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/parabElipP.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelParaboloideEliptico))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jCheckBoxParaboloideEliptico)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jCheckBoxParaboloideEliptico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelParaboloideEliptico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxParaboloideHiperbolico.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxParaboloideHiperbolico.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxParaboloideHiperbolico.setText("Paraboloide Hiperbolico");
        jCheckBoxParaboloideHiperbolico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxParaboloideHiperbolicoActionPerformed(evt);
            }
        });

        jLabelParaboloideHiperbolico.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabelParaboloideHiperbolico.setText("+(c*(z-l))=-(((y-k)^2)/b^2)+(((x-h)^2)/a^2)");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/ParabHiperP.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jCheckBoxParaboloideHiperbolico))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelParaboloideHiperbolico)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jCheckBoxParaboloideHiperbolico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelParaboloideHiperbolico))
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelHiperboloideUnaHoja.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabelHiperboloideUnaHoja.setText("+(((x-h)^2)/a^2)+(((y-k)^2)/b^2)-(((z-l)^2)/c^2)=1");

        jCheckBoxHiperboloide1Hoja.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHiperboloide1Hoja.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxHiperboloide1Hoja.setText("Hiperboloide de una Hoja");
        jCheckBoxHiperboloide1Hoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHiperboloide1HojaActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/Hiper1HojaP.PNG"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(342, 300));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxHiperboloide1Hoja)
                    .addComponent(jLabelHiperboloideUnaHoja))
                .addGap(232, 232, 232))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBoxHiperboloide1Hoja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHiperboloideUnaHoja))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxHiperboloide2Hojas.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxHiperboloide2Hojas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jCheckBoxHiperboloide2Hojas.setText("Hiperboloide de dos Hojas");
        jCheckBoxHiperboloide2Hojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHiperboloide2HojasActionPerformed(evt);
            }
        });

        jLabelHiperboloideDosHojas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelHiperboloideDosHojas.setText("+(((z-l)^2)/c^2)-(((x-h)^2)/a^2)-(((y-k)^2)/b^2)=1");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/Hiper2HojasP.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxHiperboloide2Hojas)
                    .addComponent(jLabelHiperboloideDosHojas))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCheckBoxHiperboloide2Hojas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHiperboloideDosHojas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        Figuralbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(251, 102, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLICACIÓN SUPERFICIES CUÁDRICAS Y CÁLCULO VECTORIAL");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/view/logo.png"))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(251, 102, 3));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SUPERFICIES CUÁDRICAS Y ECUACIONES");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Seleccione la ecuación:");

        jPanel11.setBackground(new java.awt.Color(251, 102, 3));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TRAZAS ENCONTRADAS");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectocalculo/design/logo1.png"))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(251, 102, 3));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("REPRESENTACIÓN GRÁFICA");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(197, 197, 197)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Figuralbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 16, 16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addComponent(Figuralbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String ecuacion = jTextField1.getText();
        Ecuacion ecuacionObj = new Ecuacion();
        String resultado = ecuacionObj.identificarEcuacion1(new Ecuacion(ecuacion));
        
        
        if(resultado.contains("La ecuacion es una paraboloide eliptica en")){
            metodoElipX();
        }else if(resultado.contains("es hiperboloide de 1 hoja")){
            metodoHip1();
        }else if(resultado.contains("es hiperboloide de 2 hojas")){
           metodoHip2();
        }else if(resultado.contains("Es un cono")){
           metodoCono();
        }else if(resultado.contains("La ecuacion es una paraboloide hiperbolica en")){
           metodoParabH();
        }else if(resultado.contains("La ecuacion es un Elipsoide")){
            metodoElip();
        }else if(resultado.contains("La ecuacion es una Esfera")){
            metodoEsf();
        }
        
        
        
        
        jTextAreaResultados.setText(resultado);
        }/*catch(NullPointerException ex){
            
            JOptionPane.showMessageDialog(null,"Ingrese valores validos null","ERROR",JOptionPane.WARNING_MESSAGE );
        }*/catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Ingrese valores validos numero","ERROR",JOptionPane.WARNING_MESSAGE);  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBoxEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEsferaActionPerformed
        if (jCheckBoxEsfera.isSelected()) {
            jTextField1.setText(jLabelEsfera.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxEsferaActionPerformed

    private void jCheckBoxElipsoideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxElipsoideActionPerformed
        if (jCheckBoxElipsoide.isSelected()) {
            jTextField1.setText(jLabelElipse.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxElipsoideActionPerformed

    private void jCheckBoxConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxConoActionPerformed
        if (jCheckBoxCono.isSelected()) {
            jTextField1.setText(jLabelCono.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxConoActionPerformed

    private void jCheckBoxParaboloideElipticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxParaboloideElipticoActionPerformed
        if (jCheckBoxParaboloideEliptico.isSelected()) {
            jTextField1.setText(jLabelParaboloideEliptico.getText());
            
        
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxParaboloideElipticoActionPerformed

    private void jCheckBoxParaboloideHiperbolicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxParaboloideHiperbolicoActionPerformed
        if (jCheckBoxParaboloideHiperbolico.isSelected()) {
            jTextField1.setText(jLabelParaboloideHiperbolico.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxParaboloideHiperbolicoActionPerformed

    private void jCheckBoxHiperboloide1HojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHiperboloide1HojaActionPerformed
        if (jCheckBoxHiperboloide1Hoja.isSelected()) {
            jTextField1.setText(jLabelHiperboloideUnaHoja.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxHiperboloide1HojaActionPerformed

    private void jCheckBoxHiperboloide2HojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHiperboloide2HojasActionPerformed
        if (jCheckBoxHiperboloide2Hojas.isSelected()) {
            jTextField1.setText(jLabelHiperboloideDosHojas.getText());
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jCheckBoxHiperboloide2HojasActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

    
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculo().setVisible(true);
            }
        });
    }
    
    
 
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Figuralbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxCono;
    private javax.swing.JCheckBox jCheckBoxElipsoide;
    private javax.swing.JCheckBox jCheckBoxEsfera;
    private javax.swing.JCheckBox jCheckBoxHiperboloide1Hoja;
    private javax.swing.JCheckBox jCheckBoxHiperboloide2Hojas;
    private javax.swing.JCheckBox jCheckBoxParaboloideEliptico;
    private javax.swing.JCheckBox jCheckBoxParaboloideHiperbolico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCono;
    private javax.swing.JLabel jLabelElipse;
    private javax.swing.JLabel jLabelEsfera;
    private javax.swing.JLabel jLabelHiperboloideDosHojas;
    private javax.swing.JLabel jLabelHiperboloideUnaHoja;
    private javax.swing.JLabel jLabelParaboloideEliptico;
    private javax.swing.JLabel jLabelParaboloideHiperbolico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultados;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
